default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: root

development:
  <<: *default
  database: litmus_status_development

test:
  <<: *default
  database: litmus_status_test

production:
  <<: *default
  database: litmus_status
